homepage = https://github.com/davlgd/exheres
summary = davlgd’s supplemental repository
description = davlgd’s tasty exhereses
owner = David Legrand <1110600+davlgd@users.noreply.github.com>
status = third-party
